Resources:
  DockerSwarmTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: DockerSwarmTemplate
      LaunchTemplateData:
        KeyName: vockey
        SecurityGroupIds: # Use SecurityGroupIds instead of SecurityGroups
          - !ImportValue CSNetworkDock:CSSecurityGroup
        InstanceType: t2.micro 
        ImageId: ami-0ebfd941bbafe70c6
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            systemctl enable docker
            sudo chmod 666 /var/run/docker.sock
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker swarm init
  DockerSwarmMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref DockerSwarmTemplate
        Version: !GetAtt DockerSwarmTemplate.DefaultVersionNumber
      AvailabilityZone: !ImportValue CSNetworkDock:AvailabilityZone1
      SubnetId: !ImportValue CSNetworkDock:CSPubSubnet1
      Tags:
        - Key: Name
          Value: DockerSwarmMaster
