Parameters:
  BucketName:
    Description: Please enter the name of the bucket
    Type: String
    Default: cs-bucket-cespec-cirrostratus

Resources:
  CSBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
#      AccessControl: PublicRead
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: '404'
            RedirectRule:
              ReplaceKeyWith: error.html

  BucketPolicy:    
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CSBucket
                - /*
      Bucket: !Ref CSBucket

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt CSBucket.WebsiteURL

  CSBucketName:
    Description: Name of the S3 bucket
    Value: !Ref CSBucket
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CSBucketName ] ]