Description: Template for an Autoscaling group for CS instances with scaling rules
Parameters:
  NetworkStackName:
    Description: Please enter the name of the Stack made with AWSB_EC2.yml.
    Type: String
    Default: CSEC2Template

Resources:
  CSLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: CS
      Subnets:
        - !ImportValue CSNetwork:CSPubSubnet1
        - !ImportValue CSNetwork:CSPubSubnet2
      SecurityGroups:
        - !ImportValue CSRDS:CSRDSSecurityGroupId
      Tags:
        - Key: Name
          Value: CSLoadBalancer

  CSLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CSLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CSTargetGroup

  CSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: CSTargetGroup
      VpcId: !ImportValue CSNetwork:CSVPC
      Port: 80
      Protocol: HTTP

  CSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !ImportValue CSEC2Template:CSLaunchTemplate
        Version: !ImportValue CSEC2Template:CSLaunchTemplateVersion
      DesiredCapacity: '2'
      MaxSize: '10'
      MinSize: '1'
      VPCZoneIdentifier:
        - !ImportValue CSNetwork:CSPubSubnet1
        - !ImportValue CSNetwork:CSPubSubnet2
      TargetGroupARNs:
        - !Ref CSTargetGroup
      Tags:
        - Key: Name
          Value: EC2Instance
          PropagateAtLaunch: true
      

  CSScaleUP: # scales up
    Type: "AWS::AutoScaling::ScheduledAction"
    Properties: 
      AutoScalingGroupName: !Ref CSAutoScalingGroup
      DesiredCapacity: '9' 
      MinSize: '1' 
      MaxSize: '10' 
      Recurrence: "0 22 * * *" # Eastern Time
  
  CSScaleDown: # scales down
    Type: "AWS::AutoScaling::ScheduledAction"
    Properties:
      AutoScalingGroupName: !Ref CSAutoScalingGroup
      DesiredCapacity: '2' 
      MinSize: '1' 
      MaxSize: '10' 
      Recurrence: "0 0 * * *" # Eastern Time