Description: Template for EC2 instance with ToDo app (the EC2 instance launches, but the app does not deploy)

Resources:
    CSEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            BlockDeviceMappings: 
            - DeviceName: "/dev/xvda"
              Ebs:
                DeleteOnTermination: true 
                VolumeType: gp3
                VolumeSize: 30
                Encrypted: "true" 
            InstanceType: t2.micro 
            ImageId: ami-0ebfd941bbafe70c6 #Needs to be AMI 2023
            KeyName: vockey 
            SubnetId: !ImportValue CSNetwork:CSPubSubnet1 #Deploy the instance in the public subnet
            UserData: 
                Fn::Base64: 
                    !Sub |
                        #!/bin/bash
                        yum update -y
                        git clone https://github.com/TimothySealy/cac-simple-webapp.git
                        cd cac-simple-webapp
                        npm install
                        npm run start
            Tags:
                -Key: Name
                Value: CSEC2Instance

Outputs:
    EC2InstanceId:
        Description: ""
        Value: !Ref CSEC2Instance
        Export:
            Name: !Join [ ":", [ !Ref "AWS::StackName", EC2InstanceId ] ] 