Parameters:
  BackupBucketName:
    Description: Please enter the name of the backup bucket
    Type: String
    Default: cs-bucket-cespec-backup2

Resources:
  CSBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BackupBucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration: 
        Rules:
          - Id: CleanupOldBackups
            Status: Enabled
            ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 30 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CSBackupBucketName:
    Value: !Ref CSBackupBucket
    Description: Name of the S3 Backup Bucket
